# Generated by Django 2.2.3 on 2019-07-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_a_collaborator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_a_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_procurement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sales',
            field=models.BooleanField(default=True),
        ),
    ]
