# Generated by Django 2.2.3 on 2019-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190704_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_human_resource',
            field=models.BooleanField(default=False),
        ),
    ]
