# Generated by Django 2.2.3 on 2019-09-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_human_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_finance',
        ),
    ]
