# Generated by Django 2.2.3 on 2019-07-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='item_image',
            field=models.ImageField(default='quoteimages/default.jpg', upload_to='quoteimages'),
        ),
    ]
