# Generated by Django 2.2.1 on 2019-07-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quoteitem_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
