# Generated by Django 2.2.1 on 2019-07-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quoteitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_rejected_reason_type',
            field=models.CharField(blank=True, choices=[('CLIENT_HAS_A_DEBIT', 'Client has previous debit'), ('OTHER_REASONS', 'Some Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='reason_for_rejection',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
