# Generated by Django 2.2.3 on 2019-07-07 04:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190705_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='item_image',
        ),
        migrations.AddField(
            model_name='client',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quote_item_status',
            field=models.CharField(choices=[('APRSNG', 'Awaiting Processing'), ('PROCESSED', 'Processed'), ('AWAARIVAL', 'Awaiting Arrival'), ('ARRIVED', 'Arrived'), ('PENDING_FINANCE', 'Pending Approval'), ('NOTPAID_DELIVER', 'Not Paid, Allow Delivery'), ('PAID_DELIVER', 'Paid, Allow Delivery'), ('AWAITDELIVERY', 'Awaiting Delivery'), ('DELIVERED', 'Delivered'), ('NOTDELIVERED', 'Not Delivered')], default='APRSNG', max_length=20),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_location', models.CharField(default='CHERT SYSTEMS SOLUTION', max_length=1000)),
                ('delivery_type', models.CharField(blank=True, choices=[('PICK_UP', 'Pick Up'), ('DELIVER', 'Deliver')], default='PICK_UP', max_length=10)),
                ('date_delivered', models.DateField(blank=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.State')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Delivery'),
        ),
    ]
