# Generated by Django 2.2.3 on 2019-07-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delivery_delivered_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='state',
            new_name='delivered_state',
        ),
    ]
