# Generated by Django 2.2.3 on 2019-07-07 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190707_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivered_state',
            new_name='delivery_state',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
