# Generated by Django 2.2.3 on 2019-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190707_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_items',
            field=models.ManyToManyField(to='core.QuoteItem'),
        ),
    ]
