# Generated by Django 2.2.3 on 2019-07-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190714_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('APRSNG', 'Awaiting Processing'), ('AWAARIVAL', 'Awaiting Arrival'), ('ARRIVED', 'Arrived'), ('PENDING_FINANCE', 'Pending Approval'), ('NOTPAID_DELIVER', 'Not Paid, Allow Delivery'), ('PAID_DELIVER', 'Paid, Allow Delivery'), ('AWAITDELIVERY', 'Awaiting Delivery'), ('DELIVERED', 'Delivered'), ('NOTDELIVERED', 'Not Delivered')], default='APRSNG', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('PICK_UP', 'Pick Up'), ('DELIVER', ' We Deliver')], default='PICK_UP', max_length=10),
        ),
    ]
