# Generated by Django 2.2.3 on 2019-07-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190714_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonNotToDeliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('PRSNG', 'Processing'), ('APRSNG', 'Awaiting Processing'), ('AWAARIVAL', 'Awaiting Arrival'), ('ARRIVED', 'Arrived'), ('PENDING_FINANCE', 'Pending Approval'), ('NOTPAID_DELIVER', 'Not Paid, Allow Delivery'), ('PAID_DELIVER', 'Paid, Allow Delivery'), ('AWAITDELIVERY', 'Awaiting Delivery'), ('DELIVERED', 'Delivered'), ('NOTDELIVERED', 'Not Delivered')], default='APRSNG', max_length=20),
        ),
    ]
