# Generated by Django 2.2.3 on 2019-07-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190716_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='not_delivered_why',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ReasonNotToDeliver'),
        ),
    ]
