# Generated by Django 2.2.3 on 2019-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delivery_not_delivered_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='other_reasons',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
