# Generated by Django 2.2.3 on 2019-08-14 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delivery_other_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date_eta',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('PRSNG', 'Processing'), ('APRSNG', 'Awaiting Processing'), ('AWAARIVAL', 'Awaiting Arrival'), ('ARRIVED', 'Arrived'), ('PARTIAL_ARRIVAL', 'Partial Arrival'), ('PARTIAL_DELIVERY', 'Partial Delivery'), ('PENDING_FINANCE', 'Pending Approval'), ('NOTPAID_DELIVER', 'Not Paid, Allow Delivery'), ('PAID_DELIVER', 'Paid, Allow Delivery'), ('AWAITDELIVERY', 'Awaiting Delivery'), ('DELIVERED', 'Delivered'), ('NOTDELIVERED', 'Not Delivered')], default='APRSNG', max_length=20),
        ),
    ]
