# Generated by Django 2.2.1 on 2019-09-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190814_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
