# Generated by Django 2.2.3 on 2019-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_quote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('PRSNG', 'Processing'), ('APRSNG', 'Awaiting Processing'), ('AWAARIVAL', 'Awaiting Arrival'), ('ARRIVED', 'Arrived'), ('PARTIAL_ARRIVAL', 'Partial Arrival'), ('PARTIAL_DELIVERY', 'Partial Delivery'), ('PENDING_FINANCE', 'Pending Approval'), ('NOTPAID_DELIVER', 'Not Paid, Allow Delivery'), ('PAID_DELIVER', 'Paid, Allow Delivery'), ('AWAITDELIVERY', 'Awaiting Delivery'), ('DELIVERED', 'Delivered'), ('NOTDELIVERED', 'Not Delivered'), ('ITEM_RELEASED', 'Item Released'), ('ITEM_RELEASED_CONFIRMED', 'Released Confirmed')], default='APRSNG', max_length=20),
        ),
    ]
