# Generated by Django 2.2.3 on 2019-09-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffleave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
