# Generated by Django 2.2.3 on 2019-09-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffleave', '0002_auto_20190921_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
    ]
