# Generated by Django 2.2.3 on 2019-09-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffleave', '0003_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maximum_days', models.IntegerField()),
                ('include_working_days', models.BooleanField(default=False)),
                ('start_month', models.IntegerField()),
                ('end_month', models.IntegerField()),
                ('number_of_days_to_notify', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffleave.LeaveType'),
        ),
    ]
